import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use - HueSurge',
  description: 'Terms of use and legal disclaimers for HueHub.',
};

export default function TermsOfUse() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 md:py-16 text-zinc-900 dark:text-zinc-100">
      <h1 className="text-3xl md:text-4xl font-bold mb-8">Terms of Use</h1>
      
      <div className="space-y-6 text-zinc-700 dark:text-zinc-300 leading-relaxed">
        <p className="font-medium">Last updated: January 31, 2026</p>

        <p>
          Welcome to HueSurge. By accessing or using this website, you agree to these Terms of Use. If you do not agree with these terms, please stop using the website.
        </p>

        <p>
          This website is a creative and informational tool that allows users to generate color palettes, color gradients, and perform color-related conversions. The purpose of the website is to support creativity, design exploration, experimentation, and learning related to colors. The website does not provide professional, legal, business, branding, accessibility, or compliance advice of any kind.
        </p>

        <p>
          All designs, palettes, gradients, conversions, and other outputs generated using this website are created based on user input and automated processes. You understand and agree that you are solely responsible for reviewing, validating, testing, and approving any output before using it for any purpose, including but not limited to commercial projects, branding, marketing, accessibility-sensitive applications, printing, publishing, or business use.
        </p>
        
        <p>
          The website does not guarantee the accuracy, suitability, originality, uniqueness, legality, or compliance of any generated output. Similar or identical color combinations may already exist, may be generated by other users, or may resemble existing brands, designs, or copyrighted works. You are solely responsible for ensuring that your use of any generated output does not infringe on intellectual property rights, trademarks, copyrights, or other rights of third parties.
        </p>

        <p>
          You agree to use the website fairly and in compliance with all applicable laws and regulations within your local, national, and international jurisdictions. This includes intellectual property laws, branding rules, accessibility requirements, and any other legal obligations relevant to your use case. It is your responsibility to understand and comply with these laws.
        </p>

        <p>
          The website and all its features are provided on an “as is” and “as available” basis. We make no warranties, express or implied, regarding the website, including but not limited to warranties of accuracy, reliability, fitness for a particular purpose, availability, or non-infringement. We are not responsible for any errors, omissions, or outcomes resulting from the use of the website.
        </p>

        <p>
          To the maximum extent permitted by law, we, along with our owners, contributors, partners, and associates, shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or related to your use of the website. This includes, but is not limited to, business losses, brand conflicts, legal disputes, accessibility failures, or reliance on generated colors or designs.
        </p>

        <p>
          If you choose to share, distribute, publish, or sell designs created using this website, you do so entirely at your own risk. While you retain responsibility for your designs, we assume no responsibility for how they are used or distributed.
        </p>

        <p>
          We reserve the right to modify, suspend, or discontinue any part of the website at any time without prior notice. We may also update these Terms of Use from time to time. Continued use of the website after changes are made constitutes your acceptance of the updated terms.
        </p>

        <p>
          All content on the website, including code, layout, interface design, branding, logos, and text, is owned by or licensed to us and is protected by applicable intellectual property laws. You may not copy, reproduce, or redistribute website content without prior written permission, except where permitted by law.
        </p>

        <p>
          Any contributors, collaborators, or associates connected with the website do not endorse user-generated designs, do not review or approve outputs, and assume no responsibility for how the website is used.
        </p>

        {/* <p>
          These Terms of Use shall be governed by and interpreted in accordance with the laws of [Your Country / State], without regard to conflict of law principles.
        </p> */}

         <p>
          If you have any questions regarding these Terms of Use, you may contact us at <a href="mailto:hello@huesurge.com" className="text-accent hover:underline">hello@huesurge.com</a>.
        </p>
      </div>
    </div>
  );
}
